apiVersion: apps/v1
kind: Deployment
metadata:
  name: Coupon
  labels:
    app: Coupon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Coupon
  template:
    metadata:
      labels:
        app: Coupon
    spec:
      containers:
        - name: Coupon
          image: username/Coupon:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5